# -*- coding: utf-8 -*-
"""CS441V_Project Midterm_Group Chí Tâm & Quốc Anh_GDP per country 1975_ 2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hZCc2z5AU9E_SRDTIjr4G1jgs_LO-s2L

# Midterm Project – Data Visualization
## Câu hỏi nghiên cứu: *"Sự chuyển dịch trung tâm kinh tế thế giới đã diễn ra như thế nào từ năm 1975 đến năm 2025?"*

---
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl

mpl.style.use('ggplot')
print('Matplotlib version:', mpl.__version__)

# install xlrd
!pip install xlrd

print('xlrd installed!')

"""## Đọc dữ liệu:"""

import cv2
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Import the data using the file path
filepath = '/content/drive/MyDrive/NĂM 3_2302220_ĐẠI HỌC TÂN TẠO/SPRING 2026_Năm 3_ĐH Tân Tạo/CS441V_Data Visualization_Thầy Hà/Data/GDP_1975_2025_uploaded.csv'
df = pd.read_csv(filepath)

df.head()
# tip: You can specify the number of rows you'd like to see as follows: df_can.head(10)

df.info()

# size of dataframe (rows, columns)
df.shape

df.describe()

df.head(10)

"""## Làm sạch & Chuẩn bị dữ liệu:"""

# Đảm bảo tất cả tên cột đều là kiểu string
df.columns = list(map(str, df.columns))
df.columns

# Danh sách các năm:
years = list(map(str, range(1975, 2026)))
years

# Phân nhóm thu nhập (Income Group) tự động dựa trên tứ phân vị GDP năm 2023
# Sử dụng pd.qcut để chia 4 nhóm đều nhau
df_2025_valid = df[['Country', '2025']].dropna().copy()

df_2025_valid['Income_Group'] = pd.qcut(
    df_2025_valid['2025'],
    q=4,
    labels=['Low Income (Q1)', 'Lower-Middle (Q2)', 'Upper-Middle (Q3)', 'High Income (Q4)']
)

# Gán Income_Group vào df
df = df.merge(df_2025_valid[['Country', 'Income_Group']], on='Country', how='left')
df.head()

# Tính tổng GDP tích lũy qua tất cả các năm cho mỗi quốc gia
df['Total'] = df[years].sum(axis=1, numeric_only=True)
df.head()

# # Đặt Country làm index
# df.set_index('Country', inplace=True)

df

# Tính CAGR (tốc độ tăng trưởng kép hàng năm) cho các nước có đầy đủ data từ 1975-2025
mask = df['1975'].notna() & df['2025'].notna()
df_cagr = df[mask].copy()

df_cagr['CAGR'] = ((df_cagr['2025'] / df_cagr['1975']) ** (1/50) - 1) * 100

print('Số quốc gia có đủ data 1975-2025:', mask.sum())
print('CAGR trung bình toàn cầu:', round(df_cagr['CAGR'].mean(), 2), '%')

"""
## Chart 1 - Bar Chart: Top 10 GDP Lớn Nhất - 1975 vs 2025

**Ý nghĩa:** So sánh thứ hạng top 10 nền kinh tế giữa năm 1975 và năm 2025.
Trả lời: *Quốc gia nào intop? Quốc gia nào outtop?*
"""

# Lấy top 10 năm 1975:
top10_1975 = df[['Country', '1975']].dropna().sort_values('1975', ascending=False).head(10)
top10_1975 = top10_1975.set_index('Country')
top10_1975['GDP_T'] = top10_1975['1975'] / 1e6            # đổi sang nghìn tỷ USD

# Lấy top 10 năm 2025
top10_2025 = df[['Country', '2025']].dropna().sort_values('2025', ascending=False).head(10)
top10_2025 = top10_2025.set_index('Country')
top10_2025['GDP_T'] = top10_2025['2025'] / 1e6            # đổi sang nghìn tỷ USD

print('Top 10 năm 1975:')
print(top10_1975['GDP_T'].round(2))
print()
print('Top 10 năm 2025:')
print(top10_2025['GDP_T'].round(2))

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 7))

# Subplot 1: Top 10 năm 1975
top10_1975['GDP_T'].sort_values().plot(kind='barh', ax=ax1, color='steelblue')
ax1.set_title('Top 10 GDP Thế Giới - Năm 1975')
ax1.set_xlabel('GDP (nghìn tỷ USD)')
ax1.set_ylabel('Quốc gia')


# Subplot 2: Top 10 năm 2025
top10_2025['GDP_T'].sort_values().plot(kind='barh', ax=ax2, color='coral')
ax2.set_title('Top 10 GDP Thế Giới - Năm 2025')
ax2.set_xlabel('GDP (nghìn tỷ USD)')
ax2.set_ylabel('')

plt.suptitle('CHART 1 — BAR CHART', fontsize=13, y=1.01)
plt.tight_layout()
plt.show()

print('\nGiải thích: China (vắng mặt năm 1975) nhảy vọt lên #2 năm 2025.')
print('Soviet Union biến mất. India từ ngoài Top 10 lên #4 vào năm 2025.')

"""### Kết luận rút ra từ Bar Chart:

> Sự thống trị của Mỹ: Hoa Kỳ vẫn giữ vững vị trí số 1, nhưng khoảng cách với các nước còn lại đã thay đổi đáng kể. Năm 1975, Mỹ gần gấp đôi Liên Xô và gấp ba lần Nhật Bản. Đến 2025, khoảng cách này vẫn còn, nhưng sự xuất hiện của Trung Quốc ở vị trí thứ 2 với quy mô 19.2 nghìn tỷ USD đã tạo nên một thế lưỡng cực mới về quy mô kinh tế.

> Sự trỗi dậy của châu Á: Điểm nhấn lớn nhất là sự xuất hiện của Trung Quốc (vị trí số 2) và Ấn Độ (vị trí số 4) trong top 10 năm 2025. Trong khi đó, năm 1975, Trung Quốc chỉ đứng thứ 9 và Ấn Độ còn nằm ngoài top 10. Điều này minh chứng cho sự dịch chuyển trọng tâm kinh tế về châu Á.

> Sự biến mất của các cường quốc cũ: Liên Xô và các nền kinh tế lớn của châu Âu như Pháp, Ý đã tụt hạng. Sự biến mất của Liên Xô khỏi bản đồ kinh tế là một minh chứng cho sự tan rã của một siêu cường, nhường chỗ cho các nền kinh tế thị trường mới nổi.

> Kết luận trực quan: Bar chart này đã trả lời xuất sắc câu hỏi "ai vào, ai ra". Nó cho thấy một cách rõ ràng sự suy giảm tương đối của các nền kinh tế phương Tây truyền thống và sự trỗi dậy thần kỳ của các nền kinh tế châu Á, đặc biệt là Trung Quốc và Ấn Độ.

## Chart 2 — Line Chart: GDP 6 Cường Quốc (1975–2025)

**Ý nghĩa:** Cho thấy *khi nào* cán cân thay đổi.
Trả lời: *Quỹ đạo tăng trưởng diễn ra như thế nào theo thời gian?*
"""

# Chọn 6 cường quốc
countries_line = ['United States', 'China', 'Japan', 'Germany', 'India', 'United Kingdom', 'Soviet Union']

# Lấy data và transpose để plot theo năm
df_line = df[df['Country'].isin(countries_line)].set_index('Country')[years]
df_line = df_line.T / 1e6               # nghìn tỷ USD
df_line.index = df_line.index.map(int)

df_line.head()

df_line.plot(kind='line', figsize=(14, 7))

plt.title('CHART 2 — LINE CHART\nGDP 6 Cường Quốc (1975–2025)', fontsize=13)
plt.ylabel('GDP (nghìn tỷ USD)')
plt.xlabel('Năm')
plt.legend(title='Quốc gia', loc='upper left')

# Đánh dấu năm 2010 - China vượt Japan
plt.axvline(x=2010, color='red', linestyle='--', alpha=0.5)
plt.text(2010.5, 8, '2010:\nChina vượt Japan', color='red', fontsize=9)

plt.show()

print('\nGiải thích: Năm 2010 là cột mốc lịch sử - China vượt Japan.')
print('Từ 2005 đến 2025, China tăng từ $2.3T lên $19.2T (tăng ~8x).')
print('Nhật Bản gần như đứng yên từ 1995 đến nay.')

"""### Kết luận rút ra từ Line Chart:

> Về Nhật Bản: Đường GDP của Nhật Bản cho thấy sự tăng trưởng thần kỳ từ sau Thế chiến II, đạt đỉnh vào những năm 1990 và sau đó "đứng yên" trong suốt 3 thập kỷ tiếp theo. Đây là một bài học kinh tế vĩ mô sâu sắc về già hóa dân số.

> Về Trung Quốc: Đường cong tăng trưởng của Trung Quốc, đặc biệt sau năm 2001 (gia nhập WTO) gần như dựng đứng, cho thấy tốc độ tăng trưởng đỉnh cao trong lịch sử. Nó vượt qua lần lượt các cường quốc châu Âu và Nhật Bản để vươn lên vị trí thứ hai.

> Về Mỹ và châu Âu: Mỹ duy trì đà tăng trưởng ổn định, liên tục. Các nền kinh tế châu Âu như Đức và Anh có tăng trưởng nhưng với tốc độ chậm hơn nhiều, phản ánh sự ổn định của các nền kinh tế phát triển.

## Chart 3 — Pie Chart: Thị Phần GDP Toàn Cầu — 1975 vs 2025

**Ý nghĩa:** Thể hiện rõ nhất sự *dịch chuyển tỉ trọng* của các nền kinh tế thế giới.
Trả lời: *Quốc gia nào đang chiếm nhiều hơn / ít hơn tổng GDP thế giới?*
"""

# Hàm tính thị phần top N + Others
def get_pie_data(year, top_n=10):
    s = df[['Country', year]].dropna().sort_values(year, ascending=False)
    top = s.head(top_n).copy()
    other_val = s.iloc[top_n:][year].sum()
    top.loc[len(top)] = ['Others / Khác', other_val]
    top = top.set_index('Country')
    top['GDP_T'] = top[year] / 1e6
    return top

pie_1975 = get_pie_data('1975')
pie_2025 = get_pie_data('2025')

print('Năm 1975:')
print(pie_1975['GDP_T'].round(2))

print('\nNăm 2025:')
print(pie_2025['GDP_T'].round(2))

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 8))

# Pie 1975
pie_1975['GDP_T'].plot(kind='pie',
                       ax=ax1,
                       autopct='%1.1f%%',
                       startangle=90,
                       shadow=False,
                       pctdistance=0.75)
ax1.set_title('Tỉ trọng GDP Toàn Cầu\n1975', fontsize=12)
ax1.set_ylabel('')

# Pie 2025
pie_2025['GDP_T'].plot(kind='pie',
                       ax=ax2,
                       autopct='%1.1f%%',
                       startangle=90,
                       shadow=False,
                       pctdistance=0.75)
ax2.set_title('Tỉ trọng GDP Toàn Cầu\n2025', fontsize=12)
ax2.set_ylabel('')

plt.suptitle('CHART 3 — PIE CHART\nTỉ trọng GDP Thế Giới Đã Thay Đổi Như Thế Nào?', fontsize=13, y=1.01)
plt.tight_layout()
plt.show()

print('\nGiải thích: Năm 1975 USA chiếm ~25%, 2025 tăng nhẹ lên ~27%.')
print('China tăng từ ~2.5% lên ~17%. Đây là 1 thay đổi lớn nhất trong lịch sử kinh tế hiện đại.')

"""### Kết luận rút ra từ Pie Chart:

> Sự thu hẹp của phần Others: Năm 1975, nhóm "Others / Khác" chiếm tới 28.7% . Đến 2025, con số này tăng lên 36.56 tỷ USD nhưng tỷ trọng có thể đã thay đổi do tổng GDP toàn cầu tăng lên. Điều này cho thấy sự đa cực hóa của nền kinh tế thế giới.

> Sự mở rộng của Trung Quốc: Thị phần của Trung Quốc tăng từ ~2.5% lên ~17% là một cú nhảy vọt lịch sử. Không có quốc gia nào trong lịch sử hiện đại có thể gia tăng thị phần GDP toàn cầu nhanh và mạnh như vậy trong vòng 50 năm.

> Sự ổn định của Mỹ: Mỹ vẫn duy trì thị phần ổn định (~25-27%), cho thấy quy mô kinh tế của họ vẫn tăng trưởng song song với tốc độ tăng trưởng chung của thế giới.

## Chart 4 — Area Chart: GDP Tích Lũy Theo Khối Kinh Tế (1975–2025)

**Ý nghĩa:** Thấy được tổng GDP toàn cầu tăng lên bao nhiêu,
và layer nào phình to nhất.
Trả lời: *Các khối kinh tế đóng góp bao nhiêu % vào tổng thế giới qua từng thập kỷ?*
"""

# Định nghĩa các khối kinh tế
blocs = {
    'USA':         ['United States'],
    'China':       ['China'],
    'EU Core':     ['Germany', 'France', 'Italy', 'Spain', 'Netherlands'],
    'Japan+Korea': ['Japan', 'South Korea'],
    'India':       ['India'],
    'ASEAN':       ['Indonesia', 'Thailand', 'Vietnam', 'Malaysia', 'Philippines', 'Singapore'],
    # 'Others':      None  # sẽ tính sau
}

# Tính GDP từng khối theo năm (nghìn tỷ USD)
bloc_data = {}
for name, countries in blocs.items():
    if countries is None:
        continue
    vals = []
    for yr in years:
        total = df[df['Country'].isin(countries)][yr].sum(min_count=1) / 1e6
        vals.append(total if not np.isnan(total) else 0)
    bloc_data[name] = vals

# # Others = Total - sum(defined blocs)
# world_total = [df[yr].sum(min_count=1)/1e6 for yr in years]
# others = [max(0, world_total[i] - sum(bloc_data[k][i] for k in bloc_data))
#           for i in range(len(years))]
# bloc_data['Others'] = others

# Tạo DataFrame
df_area = pd.DataFrame(bloc_data, index=[int(y) for y in years])
df_area.head()

df_area.plot(kind='area', stacked=True, figsize=(14, 7), alpha=0.75)

plt.title('CHART 4 — AREA CHART\nGDP Tích Lũy Theo Khối Kinh Tế (1975–2025)', fontsize=13)
plt.ylabel('GDP (nghìn tỷ USD)')
plt.xlabel('Năm')
plt.legend(title='Khối kinh tế', loc='upper left')

# Đánh dấu event quan trọng
plt.axvline(x=2001, color='green', linestyle='--', alpha=0.5)
plt.text(2001.5, 5, 'China\ngia nhập WTO', fontsize=8, color='green')

plt.show()

print('\nGiải thích: Layer China (xanh biển) mở rộng mạnh nhất từ 2001–2025.')

"""### Kết luận rút ra từ Area Chart:

> Sự bùng nổ của Trung Quốc: Lớp màu xanh biển (China) mở rộng với tốc độ rất lớn từ năm 2001. Điều này trực quan hóa tác động của hội nhập kinh tế toàn cầu đối với sự phát triển thần kỳ của Trung Quốc.

> Sự trưởng thành của ASEAN và Ấn Độ: Các khối này cũng cho thấy sự tăng trưởng ổn định và đáng kể, đóng góp vào sự dịch chuyển tổng thể về phía Đông.

> Sự ổn định của các khối phát triển: Mỹ và EU Core vẫn là những "lớp" nền tảng vững chắc, nhưng tốc độ mở rộng của chúng chậm hơn so với các khối châu Á.

> Kết luận trực quan: Area chart này cho thấy tổng GDP toàn cầu đã tăng vọt, và phần lớn sự gia tăng đó đến từ châu Á. "Layer" Trung Quốc là minh chứng rõ nhất cho sự chuyển dịch trung tâm kinh tế.

## Chart 5 - Histogram: Phân Phối CAGR

**Ý nghĩa:** Đặt các kỳ lân Châu Á vào bối cảnh thống kê toàn cầu.
Trả lời: *CAGR gần 10% của Vietnam/China có thực sự ngoại lệ so với phần còn lại không?*
"""

display(df_cagr[['Country', 'CAGR']])

cagr_vals = df_cagr['CAGR']

count, bin_edges = np.histogram(cagr_vals, 10)

cagr_vals.plot(kind='hist',
               figsize=(12, 6),
               bins=20,
               color='steelblue',
               alpha=0.75,
               xticks=bin_edges)

plt.title('CHART 5 - HISTOGRAM\nPhân Phối CAGR GDP (1975–2025) - 160 Quốc Gia', fontsize=13)
plt.ylabel('Số quốc gia')
plt.xlabel('CAGR (% / năm)')

# Đường mean và median
plt.axvline(x=cagr_vals.mean(),   color='red',   linestyle='--', label=f'Mean: {cagr_vals.mean():.1f}%')
plt.axvline(x=cagr_vals.median(), color='green', linestyle='--', label=f'Median: {cagr_vals.median():.1f}%')

# Mark Vietnam và China
vn_cagr = df_cagr[df_cagr['Country']=='Vietnam']['CAGR'].values[0]
cn_cagr = df_cagr[df_cagr['Country']=='China']['CAGR'].values[0]
plt.axvline(x=vn_cagr, color='orange', linestyle=':', label=f'Vietnam: {vn_cagr:.1f}%')
plt.axvline(x=cn_cagr, color='darkred', linestyle=':', label=f'China: {cn_cagr:.1f}%')

plt.legend()
plt.show()

fast = (cagr_vals >= 9).sum()
print(f'\nGiải thích: Chỉ {fast} / {len(cagr_vals)} quốc gia đạt CAGR >= 9%.')
print(f'Vietnam ({vn_cagr:.1f}%) và China ({cn_cagr:.1f}%) nằm ở đuôi phải xa - là ngoại lệ thống kê thực sự.')
print(f'Phần lớn thế giới tăng trưởng ở mức 5–8% / năm.')

cagr_vals.mean()

cagr_vals.median()

df_cagr[df_cagr['Country']=='Vietnam']['CAGR'].values[0]

df_cagr[df_cagr['Country']=='China']['CAGR'].values[0]

"""### Kết luận rút ra từ Histogram:

> Phân phối chuẩn: Phân phối CAGR có dạng gần chuẩn (bell-shaped), tập trung nhiều nhất ở mức 5-7%, cho thấy hầu hết các quốc gia đều có mức tăng trưởng kinh tế dương và ổn định trong 50 năm qua.

> Ngoại lệ: Việt Nam (~10.2%) và Trung Quốc (~10.0%) nằm ở đuôi phải của phân phối, cách xa giá trị trung bình (~6.31%). Điều này khẳng định rằng tăng trưởng của các nước này không chỉ là "cao" mà còn là "đặc biệt", ngoại lệ thống kê thực sự, chỉ có 10 trên 160 quốc gia đạt CAGR >= 9%.

> Kết luận trực quan: Histogram này đã cho thấy "Kỳ tích châu Á" không phải là một hiện tượng phổ biến. Nó là ngoại lệ cho thấy sự thành công vượt trội của một số nền kinh tế châu Á nhờ vào các chính sách phát triển và hội nhập đúng đắn.

## Chart 6 — Box Plot: Phân Phối GDP Theo Thập Kỷ (1975–2025)

**Ý nghĩa:** Cho thấy sự bất bình đẳng kinh tế giữa các quốc gia tăng hay giảm.
Trả lời: *Box ngày càng rộng = khoảng cách giàu–nghèo giữa các nước ngày càng lớn.*
"""

# Lấy GDP (tỷ USD) của tất cả nước tại 6 thập kỷ
decade_years = ['1975', '1985', '1995', '2005', '2015', '2025']

df_box = pd.DataFrame()
for yr in decade_years:
    col = df[yr].dropna() / 1e6                 # nghìn tỷ USD
    df_box[yr] = col.reset_index(drop=True)

print('Shape:', df_box.shape)
df_box.describe().round(3)

df_box.plot(kind='box', figsize=(12, 7))

plt.title('CHART 6 — BOX PLOT\nPhân Phối GDP Toàn Cầu Theo Thập Kỷ (1975–2025)', fontsize=13)
plt.ylabel('GDP (nghìn tỷ USD)')
plt.xlabel('Năm')

plt.show()

print('\nGiải thích: Median tăng đều - thế giới nói chung giàu hơn.')
print('Nhưng whisker và outlier ngày càng dài/xa - siêu cường bứt phá mạnh hơn phần còn lại.')
print('IQR (chiều cao box) mở rộng qua từng thập kỷ -> bất bình đẳng giữa các quốc gia tăng.')

# Box plot log scale để thấy rõ hơn sự phân hóa
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(12, 7))
df_box.plot(kind='box', ax=ax)
ax.set_yscale('log')

ax.set_title('CHART 6b — BOX PLOT (Log Scale)\nPhân Phối GDP - Thấy Rõ Hơn Sự Phân Hóa', fontsize=13)
ax.set_ylabel('GDP (nghìn tỷ USD, log scale)')
ax.set_xlabel('Năm')

plt.show()

print('Với log scale: thấy rõ median tăng đều,')
print('đồng thời outlier (siêu cường) ngày càng cao hơn median -> phân hóa ngày càng sâu.')

"""### Kết luận rút ra từ Box Plot:

> Ta thấy median (đường trung vị) tăng đều, chứng tỏ "thế giới nói chung đang giàu lên". Tuy nhiên, các "whisker" và "outlier" ngày càng dài, đặc biệt là ở phía trên. Điều này phản ánh một thực tế: các siêu cường kinh tế (Mỹ, Trung Quốc, Nhật Bản,...) đã tăng trưởng mạnh mẽ, bỏ xa phần còn lại.


> Kết luận trực quan: Cả hai biểu đồ box plot đều cho thấy tình trạng bất bình đẳng kinh tế giữa các quốc gia đang ngày càng gia tăng. Trong khi đa số các nước đều phát triển, một số ít nước phát triển nhanh hơn rất nhiều, tạo ra khoảng cách thu nhập bình quân đầu người ngày càng lớn trên phạm vi toàn cầu.

## Mở Rộng Phân Tích - Thêm 3 Loại Chart

| # | Chart | Ý nghĩa |
|---|---|---|
| 7 | **Word Cloud** | Quốc gia nào tăng trưởng mạnh nhất - to = CAGR cao |
| 8 | **Regression Plot** | Xu hướng tăng trưởng GDP thế giới 50 năm - seaborn regplot |
| 9 | **Choropleth Map** | Bản đồ thế giới tô màu theo GDP 2025 - folium |

### Import thư viện:
"""

import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

mpl.style.use('ggplot')

# Tính CAGR
mask = df['1975'].notna() & df['2025'].notna()
df_cagr = df[mask].copy()
df_cagr['CAGR'] = ((df_cagr['2025'] / df_cagr['1975']) ** (1/50) - 1) * 100

print('Data loaded! Shape:', df.shape)

"""### Chart 7 - Word Cloud: Những Nước Tăng Trưởng Mạnh Nhất

**Ý nghĩa:** Tên quốc gia càng to = CAGR càng cao.
Word Cloud giúp nhận ra ngay "bản đồ tăng trưởng" -
Châu Á chiếm ưu thế rõ ràng so với phần còn lại thế giới.


"""

# Cài đặt wordcloud
!pip install wordcloud --quiet
from wordcloud import WordCloud

print('WordCloud imported!')

# Tạo chuỗi text: lặp tên nước theo tỷ lệ CAGR

max_words    = 100
total_cagr   = df_cagr['CAGR'].sum()
word_string  = ''

for _, row in df_cagr.iterrows():
    country = row['Country']
    # Chỉ dùng tên 1 chữ để word cloud đẹp hơn
    if len(country.split(' ')) == 1:
        repeat = int(row['CAGR'] / total_cagr * max_words * 10)
        word_string = word_string + (country + ' ') * repeat

print('Word string created! Sample:')
print(word_string[:200])

# Tạo và hiển thị Word Cloud
wordcloud = WordCloud(
    background_color='white',
    max_words=200,
    width=800,
    height=400
).generate(word_string)

# Hiển thị:
fig = plt.figure()
fig.set_figwidth(14)
fig.set_figheight(8)

plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('''CHART 7 - WORD CLOUD
Các Quốc Gia Tăng Trưởng GDP Nhanh Nhất (1975–2025)

          (Chữ to = CAGR cao = Tăng trưởng nhanh hơn)''',
          fontsize=13, pad=15)
plt.show()

print('\nGiải thích: Các nước Châu Á (Vietnam, China, Laos, Singapore...) xuất hiện với size lớn - đây là bằng chứng trực quan nhất cho sự trỗi dậy của các quốc gia Châu Á.')

"""### Kết luận rút ra từ Word Cloud:


> Châu Á thống trị: Các tên như Vietnam, China, Singapore, India, Malaysia, Indonesia, Thailand, South Korea nổi bật với kích thước lớn nhất, một lần nữa khẳng định vai trò trung tâm của châu Á trong tăng trưởng kinh tế toàn cầu 50 năm qua.

> Sự vắng mặt của phương Tây: Các nền kinh tế phát triển như Mỹ, Đức, Anh, Pháp có kích thước nhỏ hơn nhiều, cho thấy tốc độ tăng trưởng của họ khiêm tốn hơn so với các nước đang phát triển ở châu Á.

> Kết luận trực quan: Word cloud này một lần nữa nhấn mạnh rằng động lực tăng trưởng chính của thế giới trong nửa thế kỷ qua đến từ châu Á.

### Chart 8 - Regression Plot: Xu Hướng GDP Thế Giới (1975–2025)

**Ý nghĩa:** Seaborn `regplot` vẽ scatter + đường xu hướng tuyến tính.
Cho thấy GDP toàn cầu tăng - đặc biệt sau năm 2000 khi Trung Quốc và Ấn Độ tăng mạnh
"""

import seaborn as sns

# Tạo DataFrame tổng GDP thế giới theo năm
df_world = pd.DataFrame({
    'year' : [int(y) for y in years],
    'total': [df[y].sum(min_count=1) / 1e6 for y in years]                # nghìn tỷ USD
})

print('World GDP per year:')
print(df_world[df_world['year'].isin([1975, 1985, 1995, 2005, 2015, 2025])].to_string(index=False))

# Regression Plot
fig = plt.figure()
fig.set_figwidth(12)
fig.set_figheight(6)

ax = sns.regplot(x='year', y='total', data=df_world, color='steelblue', marker='o')

plt.title(''' CHART 8 - REGRESSION PLOT
Tổng GDP Thế Giới (1975–2025) & Đường Xu Hướng''',
          fontsize=13)
plt.ylabel('Tổng GDP Thế Giới (nghìn tỷ USD)')
plt.xlabel('Năm')
plt.show()

print('\nGiải thích: Đường regression cho thấy xu hướng tăng mạnh và đều.')
print('Nhưng thực tế tốc độ tăng ngày càng nhanh (không phải tuyến tính)')

# Advanced Chia 2 giai đoạn
# Giai đoạn 1: 1975-2000 (trước toàn cầu hóa mạnh)
# Giai đoạn 2: 2000-2025 (sau khi China/India bứt phá)

df_p1 = df_world[df_world['year'] <= 2000]
df_p2 = df_world[df_world['year'] >= 2000]

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

# Subplot 1: 1975-2000
sns.regplot(x='year', y='total', data=df_p1, color='steelblue',
            marker='o', ax=ax1)
ax1.set_title('''Giai đoạn 1975–2000 (Phương Tây + Nhật thống trị)''')
ax1.set_ylabel('Tổng GDP Thế Giới (nghìn tỷ USD)')
ax1.set_xlabel('Năm')

# Subplot 2: 2000-2025
sns.regplot(x='year', y='total', data=df_p2, color='coral',
            marker='o', ax=ax2)
ax2.set_title('''Giai đoạn 2000–2025 (Châu Á trỗi dậy)''')
ax2.set_ylabel('')
ax2.set_xlabel('Năm')

plt.suptitle('''CHART 8b — REGRESSION PLOT
GDP Thế Giới Tăng Nhanh Gấp Đôi Sau Khi Châu Á Trỗi Dậy''',
             fontsize=13, y=1.02)
plt.tight_layout()
plt.show()

# Tính slope của 2 giai đoạn
import numpy as np
slope1 = np.polyfit(df_p1['year'], df_p1['total'], 1)[0]
slope2 = np.polyfit(df_p2['year'], df_p2['total'], 1)[0]
print(f'Tốc độ tăng GDP thế giới:')
print(f'  1975-2000: ${slope1:.2f}T / năm')
print(f'  2000-2025: ${slope2:.2f}T / năm  ({slope2/slope1:.2f}x nhanh hơn!)')
print()
print('\nGiải thích: Sau năm 2000, GDP thế giới tăng nhanh gấp ~2.5 lần so với giai đoạn trước.')
print('Nguyên nhân: China gia nhập WTO (2001) + India bùng nổ + ASEAN phát triển.')

"""### Kết luận rút ra từ Regression Plot:

> Đường xu hướng tổng GDP thế giới là 1 minh chứng cho quy luật lũy thừa của tăng trưởng kinh tế. Điểm gãy sau năm 2000 thể hiện một sự thay đổi cấu trúc, khi động lực tăng trưởng chính chuyển từ các nền kinh tế phát triển sang các nền kinh tế mới nổi, đặc biệt là Trung Quốc. Điều này làm cho tốc độ tăng trưởng tổng thể của thế giới tăng tốc đáng kể.

### Chart 9 - Choropleth Map: GDP Toàn Cầu Năm 2025

**Ý nghĩa:** Bản đồ thế giới tô màu theo GDP 2025 —
màu càng đậm = kinh tế càng lớn. Nhìn vào bản đồ thấy ngay
trung tâm kinh tế đang tập trung ở đâu trên thế giới.
"""

# Cài đặt folium nếu chưa có
!pip install folium --quiet
import folium

print('Folium imported! Version:', folium.__version__)

# Chuẩn bị dữ liệu cho choropleth
# Lấy GDP 2025 của từng nước (triệu USD)
df_choro = df[['Country', '2025']].dropna().copy()
df_choro.columns = ['Country', 'GDP_2025']

# Một số tên nước cần map lại cho khớp với GeoJSON
country_name_map = {
    'United States'   : 'United States of America',
    'Congo'           : 'Republic of the Congo',
    'DR Congo'        : 'Democratic Republic of the Congo',
    'Ivory Coast'     : "Côte d'Ivoire",
    'Czech Republic'  : 'Czech Republic',
    'South Korea'     : 'South Korea',
    'North Korea'     : 'North Korea',
    'Russia'          : 'Russia',
}
df_choro['Country'] = df_choro['Country'].replace(country_name_map)

print('Số nước có data GDP 2025:', len(df_choro))
print()
print('Top 10 GDP 2025:')
print(df_choro.nlargest(10, 'GDP_2025')[['Country', 'GDP_2025']].assign(
    GDP_T=lambda x: x['GDP_2025']/1e6).drop('GDP_2025',axis=1).to_string(index=False))

df_years = df[['Country'] + years].copy()
df_years.head()

countries_with_missing_data = df_years[df_years[years].isnull().any(axis=1)]['Country'].tolist()

print(f"There are {len(countries_with_missing_data)} countries with incomplete GDP data between 1975 and 2025:")
print(countries_with_missing_data)

#  Download GeoJSON file
# Dùng wget download file)
!wget --quiet https://raw.githubusercontent.com/datasets/geo-countries/master/data/countries.geojson -O world_countries.geojson

print('GeoJSON file downloaded!')

# Tạo Choropleth Map — GDP 2025

import json

world_geo = 'world_countries.geojson'

# Load the GeoJSON file to inspect its properties
with open(world_geo, 'r') as f:
    geo_data = json.load(f)

# Inspect the first few features to find the correct key for country names
# For example, print the properties of the first feature
# print(geo_data['features'][0]['properties'])

# Based on common GeoJSON structures and typical Folium examples,
# 'name' or 'NAME' or 'COUNTRY' are often used for country names.
# Let's try 'name' first, or 'sovereignt' based on typical geojson files.

# Tạo world map
world_map = folium.Map(location=[20, 0], zoom_start=2)

# Choropleth: màu theo GDP 2025
choropleth_layer = folium.Choropleth(
    geo_data=world_geo,
    data=df_choro,
    columns=['Country', 'GDP_2025'],
    key_on='feature.properties.name', # Changed 'ADMIN' to 'name'
    fill_color='YlOrRd',
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name='GDP 2025 (triệu USD)',
    tooltip=folium.features.GeoJsonTooltip(fields=['name', 'GDP_2025'],
                                           aliases=['Country', 'GDP 2025 (triệu USD)'],
                                           localize=True)
).add_to(world_map)

# Hiển thị bản đồ
world_map

# Choropleth Map — So sánh GDP 1975 vs 2025
# Vẽ thêm bản đồ GDP 1975 để so sánh trực tiếp

df_choro_1975 = df[['Country', '1975']].dropna().copy()
df_choro_1975.columns = ['Country', 'GDP_1975']
df_choro_1975['Country'] = df_choro_1975['Country'].replace(country_name_map)

world_map_1975 = folium.Map(location=[20, 0], zoom_start=2)

folium.Choropleth(
    geo_data=world_geo,
    data=df_choro_1975,
    columns=['Country', 'GDP_1975'],
    key_on='feature.properties.name',
    fill_color='YlOrRd',
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name='GDP 1975 (triệu USD)',
    tooltip=folium.features.GeoJsonTooltip(fields=['name', 'GDP_1975'],
                                           aliases=['Country', 'GDP 1975 (triệu USD)'],
                                           localize=True)
).add_to(world_map_1975)

print('Bản đồ GDP 1975 - So sánh với bản đồ 2025 bên trên:')
world_map_1975

# Choropleth Map - CAGR (tốc độ tăng trưởng 50 năm)
# Bản đồ này trả lời trực tiếp: Châu Á có nhiều quốc gia màu đậm nhất = tăng nhanh nhất

df_choro_cagr = df_cagr[['Country', 'CAGR']].copy()
df_choro_cagr['Country'] = df_choro_cagr['Country'].replace(country_name_map)

world_map_cagr = folium.Map(location=[20, 0], zoom_start=2)

folium.Choropleth(
    geo_data=world_geo,
    data=df_choro_cagr,
    columns=['Country', 'CAGR'],
    key_on='feature.properties.name',             # Changed 'ADMIN' to 'name'
    fill_color='RdYlGn',
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name='CAGR GDP 1975-2025 (% mỗi năm)',
    tooltip=folium.features.GeoJsonTooltip(fields=['name', 'CAGR'],
                                           aliases=['Country', 'CAGR (%/năm)'],
                                           localize=True)
).add_to(world_map_cagr)

print('Bản đồ CAGR - Màu xanh = tăng nhanh, màu đỏ = tăng chậm:')
world_map_cagr

"""#### Bonus:"""

!pip install plotly

import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
import numpy as np

# Tạo bản đồ với Plotly Express
fig_map = px.choropleth(df_cagr,
                        locations="Country", # Tên cột chứa tên quốc gia
                        locationmode='country names', # Chế độ này sẽ tự nhận diện tên nước
                        color="CAGR",
                        hover_name="Country",
                        color_continuous_scale=px.colors.sequential.Plasma_r, # Màu sắc, dùng _r để đảo ngược
                        title='Bản đồ CAGR GDP Toàn Cầu (1975–2025)',
                        labels={'CAGR': 'CAGR (%)'})
fig_map.update_layout(geo=dict(showframe=False, showcoastlines=False))
fig_map.show()

"""### Kết luận rút ra từ Choropleth Map:

> Màu xanh đậm của khu vực châu Á, đặc biệt là Trung Quốc, Ấn Độ và Đông Nam Á, tương phản rõ rệt với phần còn lại của thế giới, đặc biệt là châu Phi và một phần Nam Mỹ. Bản đồ này không chỉ xác định "trung tâm tăng trưởng mới" là châu Á, mà còn cho thấy sự phân hóa giàu nghèo một cách rõ rệt trên phạm vi toàn cầu.

### Góc nhìn bổ sung: SEABORN – Regression Plot: Hệ số Gini theo thời gian
> **"Ngoài việc xác định chuyển dịch về những quốc gia nào, ta cũng cần hỏi: sự chuyển dịch này có làm thế giới bình đẳng hơn không?" :** Đo lường tổng quát - bất bình đẳng kinh tế giữa các quốc gia tăng hay giảm?

Chỉ số **Gini** (0 = bình đẳng tuyệt đối, 1 = bất bình đẳng tuyệt đối) tính trên GDP các quốc gia mỗi năm.
"""

# Seaborn & Regression Plots
import seaborn as sns

print('Seaborn imported!')

"""Hệ số Gini được tính bằng công thức (dạng data đã đc sắp xếp):
$$
G = \frac{2\sum_{i=1}^{n} i x_i}{n\sum_{i=1}^{n} x_i} - \frac{n+1}{n}
$$
"""

# Tính hệ số Gini cho từng năm từ data
def gini_coefficient(arr):
    """Tính Gini coefficient từ mảng giá trị GDP. Gini = 0: bình đẳng, Gini = 1: bất bình đẳng tuyệt đối."""
    arr = arr[~np.isnan(arr)]
    arr = np.sort(arr)
    n = len(arr)
    if n == 0: return np.nan
    index = np.arange(1, n + 1)
    return (2 * np.sum(index * arr) / (n * np.sum(arr))) - (n + 1) / n

# Áp dụng cho tất cả các năm
gini_series = {}
for y in years:
    gini_series[y] = gini_coefficient(df[y].values)

# Tạo DataFrame để plot
df_gini = pd.DataFrame(list(gini_series.items()), columns=['year', 'gini'])

# Tính Gini với index kiểu int (để regression hoạt động)
df_gini['year'] = df_gini['year'].astype(int)
df_gini

from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df_gini)

import seaborn as sns
ax = sns.regplot(x='year', y='gini', data=df_gini)

"""## Kết Luận - Trả Lời Câu Hỏi Nghiên Cứu: *"Sự chuyển dịch trung tâm kinh tế thế giới đã diễn ra như thế nào từ 1975 đến 2025?"*


> **Kết luận cuối:** Tất cả 9 chart cùng xác nhận một sự thật:
> Trung tâm kinh tế thế giới đã và đang dịch chuyển mạnh mẽ
> từ **Phương Tây → Châu Á**, đặc biệt là **Trung Quốc, Nam Á và Đông Nam Á**,
> trong giai đoạn 2000-2025.

CỤ THỂ:

**1975:** Mỹ + Tây Âu + Nhật Bản intop cao, chiếm hơn 50% GDP thế giới. Trung Quốc, Ấn Độ, ASEAN gần như vắng mặt trong top.

**1990-2000:** Liên Xô sụp đổ (1991), toàn cầu hóa bắt đầu. Châu Á bắt đầu nổi lên.

**2001-2010:** Trung Quốc gia nhập WTO -> bùng nổ. Năm **2010**: China vượt Japan - 1 cột mốc lịch sử.

**2010-2025:** "Kỷ nguyên Châu Á" — China (#2), India (#4), ASEAN ngày càng có trọng lượng tỏng đóng góp GDP toàn cầu.




"""

